apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: app-api
        image: ghcr.io/alexandermamaniy/kubernetes-cicd:ca08514ee164ec24a0f2493e2c7d03d8fd0843e7
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-api
  namespace: default
spec:
  selector:
    app: app-api
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
