apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-gitops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alexandermamaniy/alexandermamaniy/app-api-gitops.git
    targetRevision: HEAD
    path: gitops/basic
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true